### ISSUE TITLE
Check the render method of ImageLoad

### ISSUE THREAD

**Issue by kwoumn3** [TuNguyenThanh/react-native-image-placeholder#11]
I did an npm install of the latest `react-native-image-placeholder` and when I am running my code in the iOS simulator through Xcode, I get the following error:

<img width="376" alt="screen shot 2017-08-03 at 8 18 34 am" src="https://user-images.githubusercontent.com/7096310/28931123-ee5c6d76-7829-11e7-8ecf-f5af56a981fc.png">

Is this something I am doing wrong or is there something wrong with the library?

**Comment by kenhkelly** [comment]
Hi @kwoumn3, If you can, please share your code so we could have a better idea of what's going on.

**Comment by kwoumn3** [comment]
@kenhkelly This is how I'm using this library

```
{files.length === 1 &&
          <TouchableWithoutFeedback onPress={onPress} disabled={!imageTouchable}>
            <View style={[styles.cardMediaImages, style, { flexDirection: 'row' }]}>
              <ImageLoad
                source={{ uri: `${files[0]}` }}
                style={{ flex: 1 }}
              />
            </View>
          </TouchableWithoutFeedback>
        }
```

**Comment by kwoumn3** [comment]
I think this issue could be related to `ImageBackground` being imported from react-native. It doesn't look like there is such a component in react-native by that name

**Comment by jlcrow** [comment]
Latest version of react-native 46.x

**Comment by kwoumn3** [comment]
@jlcrow Hmm that would make sense why I am getting this error then because I am on version 0.44.0. Could you possibly point me to documentation for `ImageBackground`. I've looked at 0.46.x docs and didn't seem to find anything (http://facebook.github.io/react-native/releases/0.46/docs/getting-started.html)

**Comment by jlcrow** [comment]
Funny thing is there doesn't seem to be anything in the docs, we just started getting warnings in the simulator saying not to use children in image tags, instead use ImageBackground.
