### ISSUE TITLE
Hide placeholder after choose image

### ISSUE THREAD

**Issue by vendramini** [TuNguyenThanh/react-native-image-placeholder#4]
Hi, i've the following situation: an image placeholder feeded by 2 ways:

1. The product already has an image, so I just load in uri param.
2. The product doesn't has an image, so the user tap it and choose from gallery or take new photo.

(if 1. is true, it still has the option to tap and change image).

I start the app with uri param as 'null' (literal string, because can't be null neither '') and change it by the image's path from user choice. It load the image, but the placeholder still there.

Is right to use just one `<ImageLoad/>` to do what I need or should I split it in different situations? Like:

1. Product has image, so I do use `<ImageLoad/>`.
2. Product hasn't image, so I create `<Image/>` (native component).

Actually, I'm splitting, but i would like to use just 1 tag for all situations for simplicity.

Thanks.

**Comment by hassan-viabletree** [comment]
did you find any solution for that..? @kenhkelly  @TuNguyenThanh
