### ISSUE TITLE
Style Issue

### ISSUE THREAD

**Issue by bodasia** [TuNguyenThanh/react-native-image-placeholder#6]
can you change 
https://github.com/TuNguyenThanh/react-native-image-placeholder/blob/master/index.js#L45
to
`style={this.props.placeholderStyle ? this.props.placeholderStyle : styles.imagePlaceholderStyles}`
this is more universall

**Comment by TuNguyenThanh** [comment]
Thank @Bodasia !

**Comment by bodasia** [comment]
Thank you!
